image: node:14.15.1-buster

clone:
    depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
    services:
        docker:
            memory: 7128

    steps:
        - step: &scan
              size: 2x
              name: Scan in SonarCloud
              script:
                  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
                  - npm ci
                  - pipe: sonarsource/sonarcloud-scan:1.2.0
                  - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
              services:
                  - docker

        - step: &tagInPR
              name: Add feature tag from PR creation or update
              script:
                  - export tagName=$(echo $BITBUCKET_BRANCH | grep -Eiwo '[A-Z]+-[0-9]+' | awk -v buildUUID="$BITBUCKET_BUILD_NUMBER" '{print $1"."buildUUID}')
                  - git checkout $BITBUCKET_COMMIT
                  - git remote set-url origin https://${CI_BITBUCKET_USER}:${APP_SECRET}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
                  - git tag -f $tagName
                  - git push -f --tags

        - step: &dokku
              name: Deploy to dokku services
              description: This will deploy a git tag to paired environment. Default tags are QA[n], rc, stable
              script:
                  - export IMAGE_TAG=$(git tag -l --points-at HEAD | grep -E -i -w '[A-Z]+-[0-9]+(.?[0-9]+)?')
                  - ssh $DOKKU_REMOTE git:from-image $DOKKU_APP_NAME $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG
                  - ssh $DOKKU_REMOTE cleanup

        - step: &renameTag # TODO: Use a docker service with standard resources to remove the 2x size...
              services:
                  - docker
              size: 2x
              name: Add new tag to selected image
              script:
                  - export IMAGE_TAG=$(git tag -l --points-at HEAD | grep -E -i -w '[A-Z]+-[0-9]+(.?[0-9]+)?')
                  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
                  - docker pull $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG
                  - docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_IMAGE:$BITBUCKET_TAG
                  - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$BITBUCKET_TAG

        - step: &tagDeployment
              name: Tag desired status to be deployed
              description: This will deploy selected git tag to paired environment. Default tags are QA[n], rc, stable
              script:
                  - git fetch --all --tags
                  - git checkout $IMAGE_TAG
                  - git tag -f $DEPLOYMENT_TAG
                  - git push -f --tags

        - step: &dokku-legacy
              name: Deploy to dokku services in legacy mode
              script:
                  - git remote add dokku $DOKKU_REMOTE:$DOKKU_APP_NAME
                  - ssh $DOKKU_REMOTE git:set $DOKKU_APP_NAME deploy-branch $BITBUCKET_BRANCH
                  - git push -f dokku
                  - ssh $DOKKU_REMOTE cleanup

        - step: &tagInMaster
              name: Add feature tag when PR is merge in master
              script:
                  - export feature=$(git log --format=%B -n 1 | awk 'NR==1 {print $3}' | grep -Eiwo '[A-Z]+-[0-9]+')
                  - git remote set-url origin https://${CI_BITBUCKET_USER}:${APP_SECRET}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
                  - git tag -f $feature
                  - git push -f --tags

pipelines:
    pull-requests:
        '*/*-*':
            - parallel:
                  - step: *scan
                  - step: *tagInPR

    branches:
        master:
            - step: *tagInMaster

        develop:
            - step: *tagInMaster

    tags:
        'QA1':
            - parallel:
                  - step:
                        <<: *dokku
                        deployment: QA1
                        name: Deploying to QA1 environment
                  - step: *renameTag

        'QA2':
            - parallel:
                  - step:
                        <<: *dokku
                        deployment: QA2
                        name: Deploying to QA2 environment
                  - step: *renameTag

        'staging':
            - parallel:
                  - step:
                        <<: *dokku
                        deployment: staging-triporate
                        name: Deploying to production staging environment
                  - step:
                        <<: *dokku
                        deployment: staging-bcd
                        name: Deploying to bcd staging environment
                  - step: *renameTag

        'production':
            - parallel:
                  #   - step:
                  #         <<: *dokku
                  #         deployment: production-triporate
                  #         name: Deploying to triporate production environment
                  - step:
                        <<: *dokku
                        deployment: production-bcd
                        name: Deploying to bcd production environment
                  - step: *renameTag

        '/^v([0-9.]+)$/':
            - step: *renameTag

        '/^rc([0-9.]+)$/':
            - step: *renameTag

    custom:
        generic-deployment:
            - variables:
                  - name: DEPLOYMENT_TAG
                  - name: IMAGE_TAG
            - parallel:
                  - step: *tagDeployment

        # Legacy deployments
        deployment-to-staging-legacy:
            - step:
                  <<: *dokku-legacy
                  deployment: Staging
                  name: Deploying discovery-service to staging

        STAGING-deploy-to-bcd-legacy:
            - step:
                  <<: *dokku-legacy
                  deployment: bcd-staging
                  name: Deploying offers service to bcd staging environment
        deploy-to-demo-legacy:
            - step:
                  <<: *dokku-legacy
                  deployment: demo
                  name: Deploying demo

        deploy-to-triporate-prod-legacy:
            - step:
                  <<: *dokku-legacy
                  deployment: triporate-prod
                  name: Deploying triporate backend

        generic-deployment-legacy:
            - variables:
                  - name: DOKKU_REMOTE
                  - name: DOKKU_APP_NAME
            - step:
                  <<: *dokku-legacy
                  name: Deploying triporate own your way
